# Generated by Django 5.2.dev20240620164851 on 2024-06-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="securityissue",
            old_name="other_cve_type",
            new_name="other_type",
        ),
    ]
