# Generated by Django 5.2.dev20240620164851 on 2024-06-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0002_rename_other_cve_type_securityissue_other_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityissue",
            name="attack_type",
            field=models.CharField(
                choices=[
                    ("Context-dependent", "Context-dependent"),
                    ("Local", "Local"),
                    ("Physical", "Physical"),
                    ("Remote", "Remote"),
                    ("Other", "Other"),
                ],
                default="Remote",
                max_length=1024,
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="impact",
            field=models.CharField(
                choices=[
                    ("Code Execution", "Code Execution"),
                    ("Denial of Service", "Denial of Service"),
                    ("Escalation of Privileges", "Escalation of Privileges"),
                    ("Information Disclosure", "Information Disclosure"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=1024,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="securityissue",
            name="other_type",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
    ]
