# Generated by Django 5.2.dev20240620164851 on 2024-06-21 02:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0003_securityissue_attack_type_securityissue_impact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityrelease",
            name="affected_branches",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                default="{}",
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="securityrelease",
            name="who_key_id",
            field=models.CharField(default="2EE82A8D9470983E", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="securityrelease",
            name="who_key_url",
            field=models.URLField(default="https://github.com/nessita.gpg"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="securityrelease",
            name="releases",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), size=None
            ),
        ),
    ]
