# Generated by Django 5.2.dev20240626151317 on 2024-06-26 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0004_securityrelease_affected_branches_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=10)),
                ("forum_post", models.URLField()),
                (
                    "tagline",
                    models.CharField(
                        help_text="Filler to use in the sentence <i>Django [version] [tagline] which you can read about in the release notes.</i></br>For example: <i>Django 5.1 <strong>brings a kaleidoscope of improvements</strong></i>.",
                        max_length=4096,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="securityissue",
            name="description",
            field=models.TextField(
                help_text="Written in present tense.\nDo not include versions, these will be prepended automatically.\nCVE documented format suggestions:\n\n<pre>\n    •[VULNTYPE] in [COMPONENT] in [VENDOR] [PRODUCT] [VERSION] allows\n    [ATTACKER] to [IMPACT] via [VECTOR].\n\n    •[COMPONENT] in [VENDOR] [PRODUCT] [VERSION] [ROOT CAUSE], which allows\n    [ATTACKER] to [IMPACT] via [VECTOR]\n</pre>\n\nExamples:\n<pre>\n    The password hasher in contrib/auth/hashers.py allows remote attackers to\n    enumerate users via a timing attack involving login requests.\n\n    The intcomma template filter is subject to a potential denial-of-service\n    attack when used with very long strings.\n\n    The django.contrib.auth.forms.UsernameField is subject to a potential\n    denial-of-service attack via certain inputs with a very large number of\n    Unicode characters (because the NFKC normalization is slow on Windows).\n</pre>\n"
            ),
        ),
        migrations.CreateModel(
            name="BetaRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("when", models.DateTimeField()),
                ("who", models.CharField(max_length=1024)),
                ("who_key_id", models.CharField(max_length=100)),
                ("who_key_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature_release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generator.featurerelease",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
