# Generated by Django 5.2.dev20240723185001 on 2024-07-24 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0006_alter_securityissue_reporter"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseCandidateRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("when", models.DateTimeField()),
                ("who", models.CharField(max_length=1024)),
                ("who_key_id", models.CharField(max_length=100)),
                ("who_key_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature_release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generator.featurerelease",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
