# Generated by Django 5.2.dev20240723185001 on 2024-07-24 13:16

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0008_rename_releases_securityrelease_versions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="featurerelease",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="featurerelease",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="featurerelease",
            name="when",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 24, 13, 15, 41, 471931, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="featurerelease",
            name="who",
            field=models.CharField(default="Natalia Bidart", max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="featurerelease",
            name="who_key_id",
            field=models.CharField(default="2EE82A8D9470983E", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="featurerelease",
            name="who_key_url",
            field=models.URLField(default="https://github.com/nessita.gpg"),
            preserve_default=False,
        ),
    ]
