# Generated by Django 4.2.15.dev20240725022537 on 2024-07-25 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0010_betarelease_is_lts_betarelease_verbose_version_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BugFixRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=10)),
                ("verbose_version", models.CharField(max_length=100)),
                ("is_lts", models.BooleanField(default=False)),
                ("when", models.DateTimeField()),
                ("who", models.CharField(max_length=1024)),
                ("who_key_id", models.CharField(max_length=100)),
                ("who_key_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature_release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generator.featurerelease",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AlphaRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=10)),
                ("verbose_version", models.CharField(max_length=100)),
                ("is_lts", models.BooleanField(default=False)),
                ("when", models.DateTimeField()),
                ("who", models.CharField(max_length=1024)),
                ("who_key_id", models.CharField(max_length=100)),
                ("who_key_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature_release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generator.featurerelease",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
