# Generated by Django 4.2.15.dev20240725022537 on 2024-07-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0011_bugfixrelease_alpharelease"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bugfixrelease",
            name="verbose_version",
        ),
        migrations.RemoveField(
            model_name="featurerelease",
            name="verbose_version",
        ),
        migrations.RemoveField(
            model_name="securityrelease",
            name="verbose_version",
        ),
    ]
