# Generated by Django 5.2.dev20241119143005 on 2024-11-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "generator",
            "0013_securityrelease_hashes_alter_securityissue_cve_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityrelease",
            name="hashes",
            field=models.JSONField(default=dict),
        ),
    ]
