# Generated by Django 5.2.dev20241218192544 on 2024-12-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0014_alter_securityrelease_hashes"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityissue",
            name="blogdescription",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="securityrelease",
            name="hashes",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
