# Generated by Django 6.0.dev20250305152038 on 2025-03-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0017_releaser_instead_of_who"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alpharelease",
            name="who",
        ),
        migrations.RemoveField(
            model_name="alpharelease",
            name="who_key_id",
        ),
        migrations.RemoveField(
            model_name="alpharelease",
            name="who_key_url",
        ),
        migrations.RemoveField(
            model_name="betarelease",
            name="who",
        ),
        migrations.RemoveField(
            model_name="betarelease",
            name="who_key_id",
        ),
        migrations.RemoveField(
            model_name="betarelease",
            name="who_key_url",
        ),
        migrations.RemoveField(
            model_name="bugfixrelease",
            name="who",
        ),
        migrations.RemoveField(
            model_name="bugfixrelease",
            name="who_key_id",
        ),
        migrations.RemoveField(
            model_name="bugfixrelease",
            name="who_key_url",
        ),
        migrations.RemoveField(
            model_name="featurerelease",
            name="who",
        ),
        migrations.RemoveField(
            model_name="featurerelease",
            name="who_key_id",
        ),
        migrations.RemoveField(
            model_name="featurerelease",
            name="who_key_url",
        ),
        migrations.RemoveField(
            model_name="releasecandidaterelease",
            name="who",
        ),
        migrations.RemoveField(
            model_name="releasecandidaterelease",
            name="who_key_id",
        ),
        migrations.RemoveField(
            model_name="releasecandidaterelease",
            name="who_key_url",
        ),
        migrations.RemoveField(
            model_name="securityrelease",
            name="who",
        ),
        migrations.RemoveField(
            model_name="securityrelease",
            name="who_key_id",
        ),
        migrations.RemoveField(
            model_name="securityrelease",
            name="who_key_url",
        ),
    ]
