# Generated by Django 6.0.dev20250305152038 on 2025-03-06 20:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0018_remove_alpharelease_who_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "version",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        default=datetime.date.today,
                        help_text="Leave blank if the release date isn't know yet, typically if you're creating the final release just after the alpha because you want to build docs for the upcoming version.",
                        null=True,
                        verbose_name="Release date",
                    ),
                ),
                (
                    "eol_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if the end of life date isn't known yet, typically because it depends on the release date of a later version.",
                        null=True,
                        verbose_name="End of life date",
                    ),
                ),
                ("major", models.PositiveSmallIntegerField(editable=False)),
                ("minor", models.PositiveSmallIntegerField(editable=False)),
                ("micro", models.PositiveSmallIntegerField(editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("a", "alpha"),
                            ("b", "beta"),
                            ("c", "release candidate"),
                            ("f", "final"),
                        ],
                        editable=False,
                        max_length=1,
                    ),
                ),
                ("iteration", models.PositiveSmallIntegerField(editable=False)),
                (
                    "is_lts",
                    models.BooleanField(
                        default=False,
                        help_text='Is this an (<abbr title="Long Term Support">LTS</abbr>) release?',
                        verbose_name="Long Term Support",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="alpharelease",
            name="is_lts",
        ),
        migrations.RemoveField(
            model_name="alpharelease",
            name="version",
        ),
        migrations.RemoveField(
            model_name="betarelease",
            name="is_lts",
        ),
        migrations.RemoveField(
            model_name="betarelease",
            name="version",
        ),
        migrations.RemoveField(
            model_name="bugfixrelease",
            name="is_lts",
        ),
        migrations.RemoveField(
            model_name="bugfixrelease",
            name="version",
        ),
        migrations.RemoveField(
            model_name="featurerelease",
            name="is_lts",
        ),
        migrations.RemoveField(
            model_name="featurerelease",
            name="version",
        ),
        migrations.RemoveField(
            model_name="releasecandidaterelease",
            name="is_lts",
        ),
        migrations.RemoveField(
            model_name="releasecandidaterelease",
            name="version",
        ),
        migrations.RemoveField(
            model_name="securityrelease",
            name="is_lts",
        ),
        migrations.RemoveField(
            model_name="securityrelease",
            name="version",
        ),
        migrations.AddField(
            model_name="alpharelease",
            name="release",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="generator.release",
            ),
        ),
        migrations.AddField(
            model_name="betarelease",
            name="release",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="generator.release",
            ),
        ),
        migrations.AddField(
            model_name="bugfixrelease",
            name="release",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="generator.release",
            ),
        ),
        migrations.AddField(
            model_name="featurerelease",
            name="release",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="generator.release",
            ),
        ),
        migrations.AddField(
            model_name="releasecandidaterelease",
            name="release",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="generator.release",
            ),
        ),
    ]
