# Generated by Django 6.0.dev20250305152038 on 2025-03-07 20:52

import django.db.models.deletion
import generator.models
from django.db import migrations, models


def populate_preleases(apps, schema_editor):
    attrs = {
        "when",
        "releaser",
        "created_at",
        "updated_at",
        "release",
        "feature_release",
        "verbose_version",
    }
    PreRelease = apps.get_model("generator", "PreRelease")
    for model_name in ("AlphaRelease", "BetaRelease", "ReleaseCandidateRelease"):
        model_class = apps.get_model("generator", model_name)
        for m in model_class.objects.all():
            PreRelease.objects.create(**{i: getattr(m, i) for i in attrs})


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0021_remove_securityrelease_affected_branches_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("when", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("verbose_version", models.CharField(max_length=100)),
                (
                    "feature_release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generator.featurerelease",
                    ),
                ),
                (
                    "release",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="generator.release",
                    ),
                ),
                (
                    "releaser",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="generator.releaser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(populate_preleases, migrations.RunPython.noop),
    ]
