# Generated by Django 6.0.dev20250305152038 on 2025-03-07 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0022_prerelease"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="betarelease",
            name="feature_release",
        ),
        migrations.RemoveField(
            model_name="betarelease",
            name="release",
        ),
        migrations.RemoveField(
            model_name="betarelease",
            name="releaser",
        ),
        migrations.RemoveField(
            model_name="releasecandidaterelease",
            name="feature_release",
        ),
        migrations.RemoveField(
            model_name="releasecandidaterelease",
            name="release",
        ),
        migrations.RemoveField(
            model_name="releasecandidaterelease",
            name="releaser",
        ),
        migrations.DeleteModel(
            name="AlphaRelease",
        ),
        migrations.DeleteModel(
            name="BetaRelease",
        ),
        migrations.DeleteModel(
            name="ReleaseCandidateRelease",
        ),
    ]
