# Generated by Django 6.0.dev20250313145606 on 2025-03-13 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0024_featurerelease_eol_release_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityissue",
            name="release",
            field=models.ForeignKey(
                help_text="Security Release that will fix this issue.",
                on_delete=django.db.models.deletion.CASCADE,
                to="generator.securityrelease",
            ),
        ),
        migrations.AlterField(
            model_name="securityissue",
            name="severity",
            field=models.CharField(
                choices=[("low", "Low"), ("moderate", "Moderate"), ("high", "High")],
                default="moderate",
                max_length=128,
            ),
        ),
    ]
