# Generated by Django 5.2 on 2025-05-08 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("generator", "0027_alter_securityissue_release"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prerelease",
            name="verbose_version",
        ),
    ]
