# Generated by Django 5.2.2 on 2025-07-02 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("generator", "0028_remove_prerelease_verbose_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bugfixrelease",
            name="feature_release",
        ),
    ]
