# Generated by Django 6.1.dev20250918134405 on 2025-09-18 19:27

import django.db.models.deletion
from django.db import migrations, models

import generator.models


class Migration(migrations.Migration):
    dependencies = [
        ("generator", "0029_remove_bugfixrelease_feature_release"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releaser",
            name="key_id",
            field=models.CharField(
                help_text="gpg --list-keys --keyid-format LONG", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="securityissue",
            name="blogdescription",
            field=models.TextField(blank=True, verbose_name="Blog description"),
        ),
        migrations.AlterField(
            model_name="securityissue",
            name="cve_year_number",
            field=models.CharField(
                default=generator.models.get_cve_default, max_length=1024, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="securityissuereleasesthrough",
            name="securityissue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="generator.securityissue",
                verbose_name="Security Issue",
            ),
        ),
    ]
