# Generated by Django 5.2.2 on 2025-10-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0030_alter_releaser_key_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featurerelease",
            name="tagline",
            field=models.CharField(
                help_text="Filler to use in the sentence <i>Django [version] [tagline] which you can read about in the release notes.</i></br>For example: <i>Django 5.1 brings <strong>a kaleidoscope of improvements</strong></i>.",
                max_length=4096,
            ),
        ),
    ]
