# Generated by Django 5.2.3 on 2025-10-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generator", "0030_alter_releaser_key_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityissue",
            name="blogdescription",
            field=models.TextField(
                blank=True,
                help_text="Double backticks here.",
                verbose_name="Blog description",
            ),
        ),
        migrations.AlterField(
            model_name="securityissue",
            name="description",
            field=models.TextField(
                help_text="Written in present tense without backticks.\n==> Do not include versions, these will be prepended automatically. <==\n\nCVE documented format suggestions:\n\n<pre>\n    •[VULNTYPE] in [COMPONENT] in [VENDOR] [PRODUCT] [VERSION] allows\n    [ATTACKER] to [IMPACT] via [VECTOR].\n\n    •[COMPONENT] in [VENDOR] [PRODUCT] [VERSION] [ROOT CAUSE], which allows\n    [ATTACKER] to [IMPACT] via [VECTOR]\n</pre>\n\nExamples:\n<pre>\n    The password hasher in contrib/auth/hashers.py allows remote attackers to\n    enumerate users via a timing attack involving login requests.\n\n    The intcomma template filter is subject to a potential denial-of-service\n    attack when used with very long strings.\n\n    The django.contrib.auth.forms.UsernameField is subject to a potential\n    denial-of-service attack via certain inputs with a very large number of\n    Unicode characters (because the NFKC normalization is slow on Windows).\n</pre>\n"
            ),
        ),
        migrations.AlterField(
            model_name="securityissue",
            name="summary",
            field=models.CharField(help_text="Single backticks here.", max_length=1024),
        ),
    ]
