# Generated by Django 5.2.7 on 2025-10-20 19:20

import django.core.validators
import django.utils.timezone
from django.db import migrations, models

import generator.models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0032_alter_securityissue_blogdescription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityissue",
            name="attack_complexity",
            field=models.CharField(
                choices=[("L", "Low"), ("H", "High")],
                default="L",
                help_text="Conditions beyond attacker control required to exploit (AC)",
                max_length=8,
                verbose_name="CVSS Attack Complecity",
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="attack_requirements",
            field=models.CharField(
                choices=[("N", "None"), ("P", "Present")],
                default="N",
                help_text="Preconditions for attack to be successful (AT)",
                max_length=8,
                verbose_name="CVSS Attack Requirements",
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="attack_vector",
            field=models.CharField(
                choices=[
                    ("N", "Network"),
                    ("A", "Adjacent"),
                    ("L", "Local"),
                    ("P", "Physical"),
                ],
                default="N",
                help_text="The context by which vulnerability exploitation is possible (AV)",
                max_length=16,
                verbose_name="CVSS Attack Vector",
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="automatable",
            field=models.CharField(
                choices=[("X", "Not Defined"), ("N", "No"), ("Y", "Yes")],
                default="X",
                help_text="Ease of automation for exploit (AU)",
                max_length=16,
                verbose_name="CVSS Automatable",
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="cna",
            field=models.CharField(
                choices=[("DSF", "DSF"), ("MITRE", "MITRE")],
                default="MITRE",
                max_length=128,
                verbose_name="CNA issuing the CVE ID for this issue.",
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="confirmed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="securityissue",
            name="cvss_base_score",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text='Base score (0–10) calculated from the CVSS v4.0 metrics.</br>This value should be computed from the CVSS selected metric fields using the official CVSS v4.0 formula.</br>See <a href="https://www.first.org/cvss/calculator/4-0">https://www.first.org/cvss/calculator/4-0</a>',
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="CVSS Base Score",
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="privileges_required",
            field=models.CharField(
                choices=[("N", "None"), ("L", "Low"), ("H", "High")],
                default="N",
                help_text="Level of privileges needed to exploit (PR)",
                max_length=8,
                verbose_name="CVSS Privileges Required",
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="provider_urgency",
            field=models.CharField(
                choices=[
                    ("X", "Not Defined"),
                    ("CLEAR", "Clear"),
                    ("GREEN", "Green"),
                    ("AMBER", "Amber"),
                    ("RED", "Red"),
                ],
                default="X",
                help_text="Urgency perceived by provider to respond (U)",
                max_length=16,
                verbose_name="CVSS Urgency",
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="recovery",
            field=models.CharField(
                choices=[
                    ("X", "Not Defined"),
                    ("A", "Automatic"),
                    ("U", "User"),
                    ("I", "Irrecoverable"),
                ],
                default="X",
                help_text="Ease of recovery from the vulnerability (R)",
                max_length=16,
                verbose_name="CVSS Recovery",
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="remediator",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="reported_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="safety",
            field=models.CharField(
                choices=[("X", "Not Defined"), ("N", "Negligible"), ("P", "Present")],
                default="X",
                help_text="Potential impact on safety of humans or environment (S)",
                max_length=16,
                verbose_name="CVSS Safety",
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="sub_availability_impact",
            field=models.CharField(
                choices=[("N", "None"), ("L", "Low"), ("H", "High")],
                default="N",
                help_text="Subsequent impact on availability of system (SA)",
                max_length=8,
                verbose_name="CVSS Subsequent Availability Impact",
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="sub_confidentiality_impact",
            field=models.CharField(
                choices=[("N", "None"), ("L", "Low"), ("H", "High")],
                default="N",
                help_text="Subsequent impact on confidentiality (SC)",
                max_length=8,
                verbose_name="CVSS Subsequent Confidentiality Impact",
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="sub_integrity_impact",
            field=models.CharField(
                choices=[("N", "None"), ("L", "Low"), ("H", "High")],
                default="N",
                help_text="Subsequent impact on integrity of information (SI)",
                max_length=8,
                verbose_name="CVSS Subsequent Integrity Impact",
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="user_interaction",
            field=models.CharField(
                choices=[("N", "None"), ("P", "Passive"), ("A", "Active")],
                default="N",
                help_text="Whether user interaction is required (UI)",
                max_length=8,
                verbose_name="CVSS User Interaction",
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="value_density",
            field=models.CharField(
                choices=[("X", "Not Defined"), ("D", "Diffuse"), ("C", "Concentrated")],
                default="X",
                help_text="Control gained over resources with a single exploitation event (V)",
                max_length=16,
                verbose_name="CVSS Value Density",
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="vuln_availability_impact",
            field=models.CharField(
                choices=[("N", "None"), ("L", "Low"), ("H", "High")],
                default="N",
                help_text="Impact on availability of system (VA)",
                max_length=8,
                verbose_name="CVSS Availability Impact",
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="vuln_confidentiality_impact",
            field=models.CharField(
                choices=[("N", "None"), ("L", "Low"), ("H", "High")],
                default="N",
                help_text="Impact on confidentiality of information (VC)",
                max_length=8,
                verbose_name="CVSS Confidentiality Impact",
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="vuln_integrity_impact",
            field=models.CharField(
                choices=[("N", "None"), ("L", "Low"), ("H", "High")],
                default="N",
                help_text="Impact on integrity of information (VI)",
                max_length=8,
                verbose_name="CVSS Integrity Impact",
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="vulnerability_response_effort",
            field=models.CharField(
                choices=[
                    ("X", "Not Defined"),
                    ("L", "Low"),
                    ("M", "Moderate"),
                    ("H", "High"),
                ],
                default="X",
                help_text="Effort needed by provider to respond (RE)",
                max_length=16,
                verbose_name="CVSS Response Effort",
            ),
        ),
        migrations.AlterField(
            model_name="securityissue",
            name="attack_type",
            field=models.CharField(
                default="Remote", help_text="Deprecated.", max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name="securityissue",
            name="cve_type",
            field=models.TextField(
                help_text="Comma separated list of Common Weakness Enumeration (<strong>CWE</strong>) types.</br>Browse available types at: <a href=\"https://cwe.mitre.org/\">https://cwe.mitre.org/</a></br>Examples:</br><code>CWE-23 Relative Path Traversal</br>CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')</br>CWE-89 Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')</br>CWE-352: Cross-Site Request Forgery (CSRF)</br>CWE-117 Improper Output Neutralization for Logs</br>CWE-770 Allocation of Resources Without Limits or Throttling</code>",
                verbose_name="CWE Problem Type",
            ),
        ),
        migrations.AlterField(
            model_name="securityissue",
            name="cve_year_number",
            field=models.CharField(
                default=generator.models.get_cve_default,
                max_length=1024,
                unique=True,
                verbose_name="CVE ID",
            ),
        ),
        migrations.AlterField(
            model_name="securityissue",
            name="impact",
            field=models.TextField(
                help_text='Comma separated list of Common Attack Pattern Enumeration and Classification (<strong>CAPEC</strong>) types.</br>Browse available types at: <a href="https://capec.mitre.org/">https://capec.mitre.org/</a></br>Examples:</br><code>CAPEC-54 Query System for Information</br>CAPEC-62 Cross Site Request Forgery</br>CAPEC-63 Cross-Site Scripting (XSS)</br>CAPEC-66 SQL Injection</br>CAPEC-93 Log Injection-Tampering-Forging</br>CAPEC-491 Quadratic Data Expansion</code>',
                verbose_name="CAPEC Impact Type",
            ),
        ),
        migrations.AlterField(
            model_name="securityissue",
            name="blogdescription",
            field=models.TextField(
                blank=True,
                help_text="Double backticks here (general rst format).",
                verbose_name="Blog description",
            ),
        ),
        migrations.AlterField(
            model_name="securityissue",
            name="other_type",
            field=models.CharField(
                default="Other", help_text="Deprecated.", max_length=1024
            ),
        ),
    ]
