# Generated by Django 5.2.8 on 2025-12-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0033_securityissue_attack_complexity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityissue",
            name="cve_type",
            field=models.TextField(
                help_text="Comma separated list of Common Weakness Enumeration (<strong>CWE</strong>) types.</br>MUST CONTAIN COLON SEPARATOR!</br>Browse available types at: <a href=\"https://cwe.mitre.org/\">https://cwe.mitre.org/</a></br>Examples:</br><code>CWE-23: Relative Path Traversal</br>CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')</br>CWE-89: Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')</br>CWE-352: Cross-Site Request Forgery (CSRF)</br>CWE-117: Improper Output Neutralization for Logs</br>CWE-770: Allocation of Resources Without Limits or Throttling</code>",
                verbose_name="CWE Problem Type",
            ),
        ),
        migrations.AlterField(
            model_name="securityissue",
            name="impact",
            field=models.TextField(
                help_text='Comma separated list of Common Attack Pattern Enumeration and Classification (<strong>CAPEC</strong>) types.</br>MUST CONTAIN COLON SEPARATOR!</br>Browse available types at: <a href="https://capec.mitre.org/">https://capec.mitre.org/</a></br>Examples:</br><code>CAPEC-54: Query System for Information</br>CAPEC-62: Cross Site Request Forgery</br>CAPEC-63: Cross-Site Scripting (XSS)</br>CAPEC-66: SQL Injection</br>CAPEC-93: Log Injection-Tampering-Forging</br>CAPEC-491: Quadratic Data Expansion</code>',
                verbose_name="CAPEC Impact Type",
            ),
        ),
    ]
