# Generated by Django 6.0.1 on 2026-01-16 19:39

from django.db import migrations, models

import generator.models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0035_alter_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="checksum",
            field=models.FileField(
                blank=True,
                storage=generator.models.get_storage,
                upload_to=generator.models.upload_to_checksum,
                verbose_name="Signed checksum as a .asc file",
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="tarball",
            field=models.FileField(
                blank=True,
                storage=generator.models.get_storage,
                upload_to=generator.models.upload_to_artifact,
                verbose_name="Tarball artifact as a .tar.gz file",
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="wheel",
            field=models.FileField(
                blank=True,
                storage=generator.models.get_storage,
                upload_to=generator.models.upload_to_artifact,
                verbose_name="Wheel artifact as a .whl file",
            ),
        ),
    ]
