# Generated by Django 6.0.1 on 2026-01-19 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0036_alter_release_checksum_alter_release_tarball_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="releaser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="securityissue",
            name="cna",
            field=models.CharField(
                choices=[("DSF", "DSF"), ("MITRE", "MITRE")],
                default="DSF",
                max_length=128,
                verbose_name="CNA issuing the CVE ID for this issue.",
            ),
        ),
    ]
